api_platform:
    title: Sample Local Brand X API
    version: 1.0.0
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
        csv: ['text/csv']
    docs_formats:
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
    keep_legacy_inflector: false
    use_symfony_listeners: true
    resource_class_directories:
        - '%kernel.project_dir%/src/Employee/Infrastructure/Endpoint/ApiResource'
