framework:
    messenger:
        transports:
            async: '%env(MESSENGER_TRANSPORT_DSN)%'

        routing:
            'App\Shared\Application\Bus\Command': async

        default_bus: command.bus
        buses:
            command.bus: ~
            query.bus: ~

when@test:
   framework:
       messenger:
           transports:
               async: 'in-memory://'
